services:
  - type: web
    name: go-service
    env: docker
    rootDir: reservation-service
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSLMODE
        sync: false

  - type: web
    name: nestjs-backend
    env: docker
    rootDir: backend
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_TLS
        value: "true"
      - key: GO_SERVICE_URL
        value: http://go-service:8081
      - key: FRONTEND_URL
        value: https://inventra-chi-nine.vercel.app
      - key: JWT_SECRET
        generateValue: true
